// <auto-generated />
using System;
using ECOMMERCE.SUBMISSION.DATA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECOMMERCE.SUBMISSION.DATA.Migrations
{
    [DbContext(typeof(EcommerceDataContext))]
    [Migration("20251108071010_updateInvoice_addColumnAccountId")]
    partial class updateInvoice_addColumnAccountId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("ECOMMERCE.SUBMISSION.DATA.Account", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("created_at")
                        .HasColumnType("INTEGER");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("updated_at")
                        .HasColumnType("INTEGER");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("ECOMMERCE.SUBMISSION.DATA.Order", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("account_id")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("amount")
                        .HasColumnType("TEXT");

                    b.Property<long>("created_at")
                        .HasColumnType("INTEGER");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("specification_id")
                        .HasColumnType("TEXT");

                    b.Property<int>("status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("updated_at")
                        .HasColumnType("INTEGER");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("account_id");

                    b.HasIndex("specification_id");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("ECOMMERCE.SUBMISSION.DATA.Specification", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("account_id")
                        .HasColumnType("TEXT");

                    b.Property<long>("created_at")
                        .HasColumnType("INTEGER");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("instructions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("updated_at")
                        .HasColumnType("INTEGER");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("account_id");

                    b.ToTable("Specification");
                });

            modelBuilder.Entity("ECOMMERCE.SUBMISSION.DATA.Order", b =>
                {
                    b.HasOne("ECOMMERCE.SUBMISSION.DATA.Account", "account")
                        .WithMany("orders")
                        .HasForeignKey("account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECOMMERCE.SUBMISSION.DATA.Specification", "specification")
                        .WithMany("orders")
                        .HasForeignKey("specification_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("account");

                    b.Navigation("specification");
                });

            modelBuilder.Entity("ECOMMERCE.SUBMISSION.DATA.Specification", b =>
                {
                    b.HasOne("ECOMMERCE.SUBMISSION.DATA.Account", "account")
                        .WithMany("specifications")
                        .HasForeignKey("account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("account");
                });

            modelBuilder.Entity("ECOMMERCE.SUBMISSION.DATA.Account", b =>
                {
                    b.Navigation("orders");

                    b.Navigation("specifications");
                });

            modelBuilder.Entity("ECOMMERCE.SUBMISSION.DATA.Specification", b =>
                {
                    b.Navigation("orders");
                });
#pragma warning restore 612, 618
        }
    }
}
